gather_policy_data:
  description: >
    2025년 제21대 대통령 선거 후보들 중 {candidates}의 {issue} 관련 정책 공약을 조사해 주세요.
    각 후보의 공식 홈페이지, 언론 기사, 정책 발표문 등을 DuckDuckGo 검색을 활용하여 수집하세요.
    중복된 내용은 제거하고 핵심 공약 3~5가지를 요약하세요.
    정보가 부족할 경우 "정보 부족"이라고 명시해 주세요.
  expected_output: 후보별 공약 요약 리스트
  agent: policy_researcher

sort_by_issue:
  description: >
    수집된 공약들 중 {issue}와 직접 관련된 내용을 선별하여 정리해 주세요.
    불분명하거나 우회적인 표현은 배제하고, 정책 대상·내용·효과에 따라 그룹화 해 주세요.
  expected_output: 이슈별 핵심 정책 정리
  agent: issue_sorter

compare_policies:
  description: >
    {candidates} 후보들이 제시한 {issue} 공약을 기준별(예: 재원, 수혜계층, 실행 시기 등)로 나누어 표 형식으로 비교해 주세요.
    중복 표현은 간결하게 정리하고, 각 항목별 주요 차이점을 강조해 주세요.
  expected_output: 후보 간 비교 표
  agent: neutral_analyzer

analyze_sentiment:
  description: >
    후보들의 {issue} 공약 문장 중 감성적 표현(강한 언어, 과장된 약속, 논란 가능 표현 등)을 분석해 주세요.
    부정적·긍정적 표현을 분리하고, 뉴스나 커뮤니티에서의 반응이 있다면 간략히 요약해 주세요.
  expected_output: 감성 분석 및 논란 포인트 요약
  agent: sentiment_critic

generate_report:
  description: >
    지금까지의 공약 분석 결과를 종합하여 {region} 지역 유권자의 입장에서 이해하기 쉬운 보고서를 작성하세요.
    표현은 {perspective} 관점(중립/지지/비판)을 반영하고, 공약의 실현 가능성과 예상 효과를 간단히 언급해 주세요.
    결과는 3~5문단의 서술형 리포트 형식으로 정리하세요.
  expected_output: 유권자 맞춤형 요약 보고서
  agent: report_writer
  output_file: final_report.md
